// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJzyJpqVKEVe86yzeJXvYizi0TBYsoeWE',
    appId: '1:849542578291:web:bf3176addade302f376a06',
    messagingSenderId: '849542578291',
    projectId: 'fir-clisample',
    authDomain: 'fir-clisample.firebaseapp.com',
    storageBucket: 'fir-clisample.appspot.com',
    measurementId: 'G-YCQN0DXSH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwb040N5_eNh8x8FT1TT1-NO1XSIoDZDw',
    appId: '1:849542578291:android:a141ac8303b11b0e376a06',
    messagingSenderId: '849542578291',
    projectId: 'fir-clisample',
    storageBucket: 'fir-clisample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYtTy7idZ3VmC_yLwOIF7k0AOdrCQwj1c',
    appId: '1:849542578291:ios:520b73e9ad91654e376a06',
    messagingSenderId: '849542578291',
    projectId: 'fir-clisample',
    storageBucket: 'fir-clisample.appspot.com',
    iosBundleId: 'com.example.firebsesample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYtTy7idZ3VmC_yLwOIF7k0AOdrCQwj1c',
    appId: '1:849542578291:ios:6675630fb8a77550376a06',
    messagingSenderId: '849542578291',
    projectId: 'fir-clisample',
    storageBucket: 'fir-clisample.appspot.com',
    iosBundleId: 'com.example.firebsesample.RunnerTests',
  );
}
